version: '3'
services:
   tests:
      build: .
      depends_on:
         - postgres_test
      links:
         - postgres_test
      environment:
         DB_CONNECTION_STRING: postgresql://user:password@postgres_test:5432/testdatabase
      volumes:
         - .:/app
   postgres_test:
      image: postgres:11
      restart: always
      ports:
         - 5432:5432
      environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: password
         POSTGRES_DB: testdatabase
